### ISSUE TITLE
Electrical schematics

### ISSUE THREAD

**Issue by genfersee** [harkle/fallblatt-module#2]
Dear all, is there a schematics to connect the "SparkFun USB to RS-485 Converter" to the "new module" PCB? Thanks in advance!
Genfersee

**Comment by harkle** [comment]
Hello, you can find informations here: https://github.com/adfinis-sygroup/sbb-fallblatt/blob/master/doc/electrical_new_module.md

Connect A and B pins from the USB RS-485 converter to the A and B pins of the PCB.
