### ISSUE TITLE
Strange behaviour with 2 modules

### ISSUE THREAD

**Issue by genfersee** [harkle/fallblatt-module#4]
Hello,

I have modified the code to handle several modules. This is working good.
I have currently setup 2 modules, 1 with address 35 and the other with address 22.

The "move" command works always great and the appropriate module moves depending on the address used in the command:
fallblatt > <Buffer ff c0 23 05>   (Position 5 for module 35)

The "step " command works great when I send the following command on the bus:
fallblatt > <Buffer ff c6 23> In that case, only module 35 moves 1 step.

But the problem comes when I send the following command on the bus:
fallblatt > <Buffer ff c6 16> In that case, both modules 22 and 35 move 1 step which is incorrect...
It looks like step command reacts this bad when sending to the lower address value of the 2 modules (here 22 which is <35).

Because of this bug, I can not initialise each modules separately.
Do you have any idea why this behaviour? The command sent to UART seems however correct.. did I miss something?

Kind regards.

**Comment by genfersee** [comment]
This looks like some electrical issue (termination resistor missing). I will investigate further on my side.

**Comment by harkle** [comment]
Hello I had the same issue using two modules. If you find a way to fix this it would be amazing ;–)

**Comment by genfersee** [comment]
Hi @harkle, yes this is in fact normal, but this is not an electrical issue. Maybe protocol is not completely correct for C6 (step) command. As far as you use C0 (move) command to pilot the modules, you will not have any issue. I finally use C0 (move) command instead of C6 (step) command to initialise the modules.
