### ISSUE TITLE
License Issue

### ISSUE THREAD

**Issue by eni23** [harkle/fallblatt-module#5]
Hello

You copied the documentation from our repo: https://github.com/adfinis-sygroup/sbb-fallblatt
Since our repo is GPL licensed all derivative work needs to be in a compatible license. MIT is not compatible with GPL.

So please adjust the license to something compatible with GPL or remove our work and just paste a link to our docs. I would suggest to change to GPL, since everyone will get the work back which is based on your code.

**Comment by harkle** [comment]
Thank you very much for your comment about the license issue.

As I dont want to put my repo under GPL, I add this specific license to the "doc" folder.

Hope it okay for you.

Best
